version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/mapesa-web-ui" 
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pub" 
    directory: "/mapesa_flutter_app" 
    schedule:
      interval: "weekly"
