name: mapesa
description: Mapesa app.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sms_inbox: ^1.0.2
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.16
  dio: ">=4.0.6 <6.0.0"
  fluttertoast: ^8.1.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

